### ISSUE TITLE
ContentItem.starred (list of content block) missing from item.yaml

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/apidocs#13]
Is this missing in the schema, or obsolete in the API?

edit: Or is this a convenience-thing that only exists when querying the list of all items?

**Comment by hannesstruss** [comment]
Found the answer in the extension docs: https://github.com/the-grid/extension/blob/0.5.0/docs/protocol.md

**Comment by paulyoung** [comment]
Should we reopen this one, since the extension docs are in a private repo?

I think it would be good to add any missing info to this project.

**Comment by hannesstruss** [comment]
true. I'm not sure I know how it works and is supposed to work – @bergie can you shed some light on when `ContentItem.starred` exists?

**Comment by bergie** [comment]
We use `item.metadata.starred`
