### ISSUE TITLE
/item list response not there yet

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/apidocs#21]

**Comment by jonnor** [comment]
What does it mean? We have endpoint without spec, or vica versa?

**Comment by nickvelloff** [comment]
At the time of writing it meant an endpoint without a documented response.

**Comment by nickvelloff** [comment]
<img width="627" alt="screenshot 2015-11-26 05 01 50" src="https://cloud.githubusercontent.com/assets/885369/11415453/e161d850-93fa-11e5-9e9c-228efdc5737b.png">
