### ISSUE TITLE
Interested in running your own design system?

### ISSUE THREAD

**Issue by forresto** [the-grid/apidocs#22]
http://developer.thegrid.io/designsystem.html

How do we define that in the site config yml / chrome? Will other design systems define their own spectra for chrome to tweak?

**Comment by forresto** [comment]
@bergie @jonnor ping!

**Comment by jonnor** [comment]
I have updated the documentation with how to set it up, along with some related considerations. Included is also a command-line tool that allows changing the site config settings, and a minimal working design system example.

To provide a user interface for settings of a custom design system, one should provide a (web) app using The Grid HTTP API. The same app would be the one that switches on/off the custom design system for a given site.
