### ISSUE TITLE
JSON schema definition for rgbcolor is hexadecimal

### ISSUE THREAD

**Issue by paulyoung** [the-grid/apidocs#26]
``` json
"rgbcolor": {
  "description": "RGB color",
  "format": "rgbcolor",
  "pattern": "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
  "example": "#aa33cc",
  "type": "string"
},
```

I would expect this to have `red`, `green`, and `blue` properties.

**Comment by jonnor** [comment]
Why do you expect that?
This is entirely standard CSS color representation.

**Comment by paulyoung** [comment]
I thought it was strange for something called "rgbcolor" to not have red, green and blue components.

I wasn't thinking about CSS but imagine most people would have a similar expectation based on how prevalent the idea is.

Some examples...
- http://www.w3schools.com/cssref/css_colors.asp
- http://www.w3schools.com/cssref/css_colors_legal.asp
- http://www.w3schools.com/tags/ref_colorpicker.asp

<img width="472" alt="screen shot 2015-08-17 at 3 56 23 pm" src="https://cloud.githubusercontent.com/assets/84700/9318468/affe300c-44f8-11e5-889e-bb8c0e07d8cd.png">

<img width="222" alt="screen shot 2015-08-17 at 3 56 56 pm" src="https://cloud.githubusercontent.com/assets/84700/9318472/b353b394-44f8-11e5-8dfa-eb97b7301d6b.png">

<img width="265" alt="screen shot 2015-08-17 at 3 58 52 pm" src="https://cloud.githubusercontent.com/assets/84700/9318503/e9ff8f08-44f8-11e5-993b-0d1414cac5d7.png">

**Comment by jonnor** [comment]
@py do you have suggestion for better name?

**Comment by paulyoung** [comment]
My preference would be to either rename this to `hexcolor` or keep it as `rgbcolor` and provide the individual color components instead.

Personally, I think RGB has more cross-platform use.
