### ISSUE TITLE
site.url missing from schema

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/apidocs#28]
also should probably be listed as required: https://github.com/the-grid/apis/issues/63

**Comment by forresto** [comment]
1. So to set a custom URL, do we have to set both `domain` and `url`?
2. To unset a custom domain, do we have to set `domain` to `null` and generate `url` from `repo`?
3. Where in the code can I find the answers to :point_up:?
4. Where in the docs should I be able to RTF docs?

**Comment by forresto** [comment]
3. Where in the code can I find this?
4. Where in the docs should I be able to RTF docs?

**Comment by forresto** [comment]
(Flowhub recruitment potential: Answer API issues with screenshots and links to the graph...)

https://app.flowhub.io/#project/apis/apis_graphs_apis
![screen shot 2015-10-13 at 11 27 34 pm](https://cloud.githubusercontent.com/assets/395307/10474235/48ef2fec-7202-11e5-964d-085504526688.png)

**Comment by bergie** [comment]
`site.url` is a read-only property that the back-end provides for convenience when you read site data.

**Comment by forresto** [comment]
1. To set a custom URL, just set `domain`?
2. Can we specify https?
3. To unset a custom domain, just set `domain` to `null`?

**Comment by bergie** [comment]
@forresto 
1. Yes
2. Not at the moment, maybe in the future (though user may possibly do this with service like [Cloudflare](https://www.cloudflare.com/ssl))
3. Not supported yet (update: will be soon, just set to `null` to unset custom domain)
