### ISSUE TITLE
/user for api.thegrid.io

### ISSUE THREAD

**Issue by paulyoung** [the-grid/apidocs#32]
Apparently there is an endpoint at `api.thegrid.io/user` that returns different information than `passport.thegrid.io/api/user`

I assume that this means that [the page on Passport](http://developer.thegrid.io/passport.html) is now out of date.

Should all user operations should be made against https://api.thegrid.io instead of https://passport.thegrid.io?

**Comment by bergie** [comment]
Passport's user endpoint is the canonical one. The user endpoint on api.thegrid.io enhances this with some additional details related to the user's Grid plan

**Comment by paulyoung** [comment]
I think you're saying that `GET /user` is the only request that is valid for `api.thegrid.io`.

Any preference on how best to document this?
