### ISSUE TITLE
Roadmap access for Founding Members

### ISSUE THREAD

**Issue by upnorth** [the-grid/apidocs#40]
I just got my beta-access and have been trying out the various tools. But I study computer information systems and would really like to know more about the developer side of things. Also a lot of people getting beta-access now are very disappointed about your progress the last year and still yell "scam!" which I can sort of understand.

You should be more honest to us early investors about when you think The Grid will be commercially ready and what you plan to do until then. Or is it published somewhere that I just haven´t found yet?

**Comment by jonnor** [comment]
Hi @upnorth, apologies for the belated answer. At this time we do not have a public roadmap, unfortunately. The primary channel for official communication is the email updates to founders. There is now also a blog up on https://blog.thegrid.io/ and more week-by-week status updates go out on our Twitter https://twitter.com/thegrid

Twitter and support email are the best way to get in contact with general product questions. This repository is intended for specific technical questions, like how a particular API endpoint works or how to do X using the API.
