### ISSUE TITLE
Creating a (fully configured) site

### ISSUE THREAD

**Issue by paulyoung** [the-grid/apidocs#42]
Am I correct in thinking that it's not possible to create a fully configured site in a `POST` request?

That is, with more than just the `name` and `repo` fields but also including site configuration data.

It seems as if a site must first be created and then configured via a `PUT` request.

**Comment by jonnor** [comment]
The site has a default configuration when first created, so it can be used directly after that.
The API client should fetch and update the site configuration before putting it back, to ensure that set defaults are preserved

**Comment by bergie** [comment]
You can actually pass `config` when creating a site. The default config / shuffle will be applied for keys _not present_ in the config you give.

**Comment by paulyoung** [comment]
Thanks @bergie. I must have been doing something wrong when I tried this yesterday because I was getting a 500 response then, but I managed to make this work today.
