### ISSUE TITLE
unsalvageable measurement is undocumented

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/apidocs#63]
:trollface: 

https://github.com/the-grid/apidocs/blob/master/schemata/imagemeasurements.yaml

should this schema be somewhere be on the html docs too, or is it and I just didn't find it?

**Comment by automata** [comment]
It is already documented in https://github.com/the-grid/apidocs/blob/master/schemata/media.yaml#L79-L82.

IMHO the best way to read our schema is going through the _full schemas_, which are generated by expanding inheritances. For image blocks we have the following full schema:

https://github.com/the-grid/apidocs/blob/gh-pages/full-schema/image.json

Other _full schemas_ can be accessed at https://github.com/the-grid/apidocs/tree/gh-pages/full-schema.

**Comment by hannesstruss** [comment]
@automata Is there a way to make that easier to digest? 600 lines of nested JSON are a bit tough to parse for humans :)

**Comment by automata** [comment]
@hannesstruss yeah, what I like to do is opening the [raw schema](https://raw.githubusercontent.com/the-grid/apidocs/gh-pages/full-schema/image.json) having [JSONView extension](https://github.com/gildas-lormeau/JSONView-for-Chrome) installed. It really helps to navigate through the schema:

<img width="931" alt="screen shot 2016-10-25 at 12 04 26" src="https://cloud.githubusercontent.com/assets/49062/19689233/7305280e-9aab-11e6-81cb-f7237239764b.png">

But yeah, it would be really great to use some lib to show our schemas on docs. Maybe [this](http://mattyod.github.io/matic-draft4-example/example.html) or [that](http://lbovet.github.io/docson/index.html#/docson/examples/example.json). If you have some suggestion, please let me know.
